version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db_staging
    restart: always
    env_file:
      - .env.staging
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - db_data_staging:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app_staging
    restart: always
    env_file:
      - .env.staging
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_PORT: 3306
      APP_ENV: staging

volumes:
  db_data_staging:

networks:
  app-network:
    driver: bridge

