version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      # Truyền host database nội bộ trong mạng compose
      DB_HOST: db
      DB_PORT: 3306

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
