version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db_dev
    restart: always
    env_file:
      - .env.development
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3308:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: golang:1.22
    container_name: go_app_dev
    working_dir: /src
    restart: always
    env_file:
      - .env.development
    ports:
      - "8082:8080"
    volumes:
      - ./:/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_PORT: 3306
      APP_ENV: development
    command: bash -lc "go run github.com/air-verse/air@latest"

volumes:
  db_data_dev:

networks:
  app-network:
    driver: bridge

