version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app_prod
    restart: always
    # Trong production, không nên commit file .env.production
    env_file:
      - .env.production
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      APP_ENV: production
    command: ["/app/main"]

networks:
  app-network:
    driver: bridge

